# permissions for end users to edit sqlns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqln-editor-role
rules:
- apiGroups:
  - db.narity.com
  resources:
  - sqlns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.narity.com
  resources:
  - sqlns/status
  verbs:
  - get
